using new X-CCODE-HOME/WORK instead of language dependent country names

diff --git a/contmgr b/contmgr
--- a/contmgr
+++ b/contmgr
@@ -101,6 +101,7 @@ contain input such as this:
    Bold='DejaVuSerif-Bold'
    Input="$HOME/Contacts.vcf"
    Mycountry='Nederland'
+   Mycode=31
 
 The content shown here would have no effect, as its values are the
 defaults already.
@@ -164,7 +165,7 @@ handle_options() {
    Key='' Noarea='' Grepopt=-ril Format='term' Return=''
    Fsize=12 Font='DejaVuSerif' Bold='DejaVuSerif-Bold' Input="$HOME/Contacts.vcf"
 
-   Dot=''
+   Mycode='' Dot=''
    Mycountry='Nederland' # this is emptied except in vcard format
    # shellcheck disable=SC2153
    if [[ -n $PREFIX ]]; then
@@ -177,6 +178,7 @@ handle_options() {
    fi
    # shellcheck disable=SC1090
    [[ -e $HOME/.contmgr.conf ]] && source "$HOME/.contmgr.conf"
+   [[ -n $Mycode ]] || Warn "You did not set Mycode in any configuration file"
    
    while true; do
       case $1 in
@@ -381,7 +383,7 @@ pr_age() {
 
 :<<'DOC' #---------------------------------------------------------------------
 = pr_city
-synopsis:	 pr_city zip city state country
+synopsis:	 pr_city zip city state areacode
 description:	Try to format city, state and zip
 		if rules not known, print "city, state, zip"
 		 pr_city 4158CH Deil '' → 4158 CH Deil
@@ -389,18 +391,35 @@ description:	Try to format city, state and zip
 DOC
 #-------------------------------------------------------------------------------
 pr_city() {
+   local ccode
    [[ -z $2 ]] && return # no city = no address
-   case "$1" in
-   ([0-9][0-9][0-9][0-9][A-Z][A-Z]) # Netherlands
-         echo "${1:0:4} ${1:4:2} $2$Dot"
+   if [[ -z $4 ]]; then 
+      Warn "Missing country code for $1 $2; using $Mycode"
+      ccode=$Mycode
+   else
+      ccode=$4
+   fi
+   case "$ccode" in
+   (352) # Luxemburg
+         echo "L-${1//[L-]/} $2$Dot" # L-1234
 	 ;;
-   ([A-Z][A-Z][0-9][0-9][A-Z][A-Z]) # UK
-         echo -e "$2\n${1:0:3} ${1:3:3}$Dot"
+    (44) # UK
+         echo -e "$2\n${1%???} ${1: -3}$Dot" # all but last 3 <space> last 3
 	 ;;
-   ([A-Z][A-Z][0-9][0-9][0-9][0-9][0-9]) # USA
+    (33|43|47|49|385) # France, Austria, Germany, Croatia
+         echo "$1 $2$Dot" 
+	 ;;
+    (32) # Belgium
+         echo "B-${1//[B-]/} $2$Dot" # B-1234
+	 ;;
+    (31) # Netherlands
+         echo "${1:0:4} ${1:4:2} $2$Dot" # first 4 <space> last 2
+	 ;;
+     (1) # USA
          echo "$2 ${1:0:2} ${1:2:5}$Dot"
 	 ;;
-   (*)   echo "$2 $3$1$Dot"
+     (*) Warn "country code $ccode not expected" \
+              "please add new entry to my pr_city function"
 	 ;;
    esac
 }
@@ -511,8 +530,8 @@ description:	print in terminal format
 DOC
 #-------------------------------------------------------------------------------
 pr_term() {
-   hc=$(pr_city "$Hzip" "$Hcity" "$Hstate" "$Hcountry")
-   wc=$(pr_city "$Wzip" "$Wcity" "$Wstate" "$Wcountry")
+   hc=$(pr_city "$Hzip" "$Hcity" "$Hstate" "$Harea")
+   wc=$(pr_city "$Wzip" "$Wcity" "$Wstate" "$Warea")
    echo -e "$Nor———————————————————————————————————————————————————————————"
    printf "$Yel%-44s%-10s %-5s %s$Nor\n" "$Disp" "$Bday" "$(pr_age)" "$Aim"
    [[ -n "$Hstreet$Wstreet" ]] && printf "%-30s%-30s\n" "$Hstreet" "$Wstreet"
@@ -582,9 +601,9 @@ description:	print in home and work addresses label format
 DOC
 #-------------------------------------------------------------------------------
 pr_label() {
-   local i j street zip city state country name
+   local i j street zip city state country area name
    for i in H W; do
-      for j in street zip city state country; do
+      for j in street zip city state country area; do
          eval $j="\$$i$j"
       done
       [[ -n $street ]] || continue
@@ -594,7 +613,7 @@ pr_label() {
       trim name
       [[ -z $name ]] && name="$Org"
       echo -e "\\C\n$name$Dot\n${street//\\n/$Dot\\n}$Dot"
-      pr_city "$zip" "$city" "$state" "$country" "$Dot"
+      pr_city "$zip" "$city" "$state" "$area" "$Dot"
       [[ $country == "$Mycountry" ]] || echo "$country$Dot"
       echo
    done
@@ -660,13 +679,14 @@ pr_booklet() {
    texescape Org
    local i j street zip city state country
    for i in H W; do
-      for j in street zip city state country; do
+      for j in street zip city state country area; do
          eval $j="\$$i$j"
       done
+      # create an address only if there is a street:
       if [[ -n $street ]]; then
          adr+="$(join "\n" \
              "$street" \
-             "$(pr_city "$zip" "$city" "$state" "$country")" \
+             "$(pr_city "$zip" "$city" "$state" "$area")" \
              "${country%$Mycountry}" "|"
          )"
       fi
@@ -754,7 +774,8 @@ description:	print vcard
 DOC
 #-------------------------------------------------------------------------------
 pr_vcard() {
-   local h w i
+   local h w i hmw type
+   declare -A type=([H]=HOME [M]=CELL [W]=WORK)
    echo -e "BEGIN:VCARD\nVERSION:3.0"
    h="ADR;TYPE=HOME:;;$Hstreet;$Hcity;$Hstate;${Hzip// /};$Hcountry"
    w="ADR;TYPE=WORK:;;$Wstreet;$Wcity;$Wstate;${Wzip// /};$Wcountry"
@@ -773,16 +794,17 @@ pr_vcard() {
    [[ -n $Note ]] && echo "NOTE:$Note"
    [[ -n $Org  ]] && echo "ORG:$Org"
    set -- HOME CELL WORK
-   for i in "$Hphone" "$Mphone" "$Wphone"; do
-      [[ -n $i ]] || continue
+   for hmw in H M W; do
+      eval "i=\$${hmw}phone"
+      [[ -n $i ]] || continue # i becomes Hphone, Mphone, Wphone
       case $i in
         (0[89]00*) ;;
              (00*) i=+${i#00};;
-              (0*) i=+31${i#0};;
+              (0*) i=+$Mycode${i#0};;
               (+*) ;;
                (*) Warn "wrong phone number $i"
       esac
-      tel="TEL;TYPE=$1:$i"
+      tel="TEL;TYPE=${type[$hmw]}:$i"
       [[ $tel =~ \:$ ]] || echo "$tel"
       shift
    done
@@ -851,8 +873,6 @@ case $Format in
 (term)    ;;
 esac
 
-# initial expressions for mobile numbers
-Mob=(316 3247 3248[4-9] 3249[1-9] 33[67] 393[234] 447[45789] 491[567] 599[479][56] )
 # remove empty lines
 # insert empty line after END:VCARD as a record separator for msort.
 # remove \r for unix line endings,
@@ -872,6 +892,7 @@ while read -r file; do
          Hstreet Hzip Last Middle Mphone Nick Note Org Prefix Suffix Url Wcity \
          Wcountry Wmail Wphone Wstate Wstreet Wzip \
          ahome awork phome pcell pwork ehome ework
+	 Harea='' Warea=''
    while IFS= read -r line; do
       declare -l type
       [[ $line =~ ^item[0-9]\. ]] && line="${line/${BASH_REMATCH[0]}/}"
@@ -952,20 +973,22 @@ while read -r file; do
              ;;
          (*) Warn "Skipping address $line of unrecognized type"
          esac
+      elif [[ $line =~ ^X-CCODE-HOME:(.*) ]]; then
+         Harea=${BASH_REMATCH[1]}
+      elif [[ $line =~ ^X-CCODE-WORK:(.*) ]]; then
+         Warea=${BASH_REMATCH[1]}
       elif [[ $line =~ ^X-AIM.*:(.*)$ ]]; then
          Aim=${BASH_REMATCH[1]}
       elif [[ $line =~ ^TEL:(.*) ]]; then
          v="${BASH_REMATCH[1]}"
-         if [[ ! $v =~ ^[-()\ 0-9+]+$ ]]; then
+         if [[ ! $v =~ ^(11|14|\+)[0-9]+$ ]]; then
             Warn "$(displayname): phone number $v has wrong format"
          fi
-         v=${v//[-() ]/}
-         for e in "${Mob[@]}"; do
-            [[ $v =~ ^\+$e ]] && type='cell'
-         done
+         # v is now 11n or 114 or +nnnnn...
          filltype phome pcell pwork
-         v=${v/+31/0}
-         v=${v/+/00}
+         # remove the + from phone numbers: 
+         v=${v/+$Mycode/0} # own country: replace +countrycode with 0
+         v=${v/+/00} # foreign country: replace + with 00
          # shellcheck disable=SC2034
          case $type in
          (home) phome=1 # remember that home phone was set
